'use strict';
const assert=require('assert').strict,common=require('../../common'),{Dex}=require('../../../dist/sim/dex');let battle;
function start(mode='singles',ability='No Ability'){
 const p={species:'Venusaur',ability:'Creeping Bloom',moves:['splash','sludgewave','sludgebomb']},t={species:'Mew',ability,moves:['splash']};const team=[p,{...t,ability:'No Ability'}],other=[t,{...t}];battle=common.createBattle({formatid:mode==='ffa'?'gen9freeforall4pmistyfieldadrienn':mode==='doubles'?'gen9nofielddoublesbattle':'gen9nofieldsinglesgame'},mode==='ffa'?[team,other,other,other]:[team,other]);battle.makeChoices(...battle.sides.map(()=> 'team 12'));battle.field.terrain='';battle.randomizer=d=>d;battle.randomChance=(a,b)=>a>=b;for(const side of battle.sides)for(const p of side.active)p.hp=p.maxhp=p.baseMaxhp=4000;return[battle.p1.active[0],battle.p2.active[0]];
}
function hit(p,t,id='sludgebomb',extra={}){battle.clearActiveMove();const m=battle.dex.getActiveMove(id);Object.assign(m,{accuracy:true,willCrit:false,basePower:10,secondaries:null},extra);battle.actions.useMove(m,p,{target:t});battle.clearActiveMove();return m;}
describe('Venusaur Creeping Bloom',()=>{
 afterEach(()=>{battle?.destroy();battle=null;});
 it('replaces only Hospitality and retains full Infiltrator',()=>{assert.deepEqual(Dex.species.get('venusaur').abilities,{0:'Pollen Bloom',1:'Creeping Bloom',H:'Chlorophyll'});const[p]=start();assert(p.hasAbility('infiltrator'));assert.equal(p.getAbility().onModifyMove,battle.dex.abilities.get('infiltrator').onModifyMove);});
 it('first damaging Poison move poisons once; subsequent moves cannot reuse the charge',()=>{const[p,t]=start();hit(p,t);assert.equal(t.status,'psn');assert(p.volatiles.creepingbloomspent);t.cureStatus();hit(p,t);assert.equal(t.status,'');});
 for(const mode of ['doubles','ffa'])it('one spread move poisons every damaged foe but never allies in '+mode,()=>{const[p,t]=start(mode);hit(p,t,'sludgewave');for(const foe of p.foes())assert.equal(foe.status,'psn');for(const ally of p.allies())assert.equal(ally.status,'');for(const foe of p.foes())foe.cureStatus();hit(p,t,'sludgewave');for(const foe of p.foes())assert.equal(foe.status,'');});
 it('miss, Protect and damage immunity do not spend the charge',()=>{const[p,t]=start();hit(p,t,'sludgebomb',{accuracy:0});assert(!p.volatiles.creepingbloomspent);t.addVolatile('protect',t);hit(p,t);assert(!p.volatiles.creepingbloomspent);t.removeVolatile('protect');t.setType('Steel');hit(p,t);assert(!p.volatiles.creepingbloomspent);t.setType('Psychic');hit(p,t);assert.equal(t.status,'psn');});
 for(const mode of ['poisonimmune','abilityimmune','already','safeguard'])it('a damaging move spends the charge even when poison is blocked: '+mode,()=>{const[p,t]=start('singles',mode==='abilityimmune'?'Immunity':'No Ability');if(mode==='poisonimmune')t.setType('Poison');if(mode==='already')t.setStatus('brn',t);if(mode==='safeguard')t.side.addSideCondition('safeguard',t);hit(p,t);assert(p.volatiles.creepingbloomspent);assert.notEqual(t.status,'psn');});
 it('multiple hits do not retrigger after a Lum Berry cures the bonus poison',()=>{const[p,t]=start();t.setItem('lumberry');let statuses=0;battle.onEvent('AfterSetStatus',battle.format,()=>{statuses++;});hit(p,t,'sludgebomb',{multihit:2});assert.equal(statuses,1);assert.equal(t.status,'');assert.equal(t.item,'');});
 it('suppression prevents poison and charge use',()=>{const[p,t]=start();p.addVolatile('gastroacid',t);hit(p,t);assert.equal(t.status,'');assert(!p.volatiles.creepingbloomspent);});
 it('allied damage and non-Poison attacks do not spend the charge',()=>{const[p,t]=start('doubles');hit(p,p.allies()[0]);assert(!p.volatiles.creepingbloomspent);hit(p,t,'watergun');assert(!p.volatiles.creepingbloomspent);});
 it('switching restores the budget; changing ability does not',()=>{const[p,t]=start();hit(p,t);p.setAbility('No Ability');p.setAbility('Creeping Bloom');t.cureStatus();hit(p,t);assert.equal(t.status,'');battle.makeChoices('switch 2','move splash');battle.makeChoices('switch 2','move splash');hit(p,t);assert.equal(t.status,'psn');});
 it('Infiltrator really bypasses Substitute and screens',()=>{const[p,t]=start();t.addVolatile('substitute',t);const subhp=t.volatiles.substitute.hp;hit(p,t);assert(t.hp<4000);assert.equal(t.volatiles.substitute.hp,subhp);assert.equal(t.status,'psn');const m=battle.dex.getActiveMove('sludgebomb');battle.singleEvent('ModifyMove',p.getAbility(),p.abilityState,m,p,t);t.side.addSideCondition('lightscreen',t);battle.setActiveMove(m,p,t);assert.equal(battle.runEvent('ModifyDamage',p,t,m,1000),1000);battle.clearActiveMove();});
 it('normal move secondaries remain intact',()=>{const[p,t]=start();const m=hit(p,t,'sludgebomb',{secondaries:[{chance:30,status:'psn'}]});assert.equal(m.secondaries[0].chance,30);assert.equal(m.secondaries[0].status,'psn');});
});
