'use strict';
const assert=require('assert').strict,common=require('../../common');
describe('Malice Well',()=>{
 let b;afterEach(()=>b?.destroy());
 function setup(ability='Soul Cremation',ffa=false){const p={species:'Chandelure',ability,moves:['splash','protect','haze']},t={species:'Mew',ability:'No Ability',moves:['watergun','splash']};let teams=ffa?[[p,p],[t,t],[t,t],[t,t]]:[[p,p],[t,t]];b=common.createBattle({formatid:ffa?'gen9freeforall4pmistyfieldadrienn':'gen9nofieldsinglesgame'},teams);b.makeChoices(...teams.map(()=> 'team 12'));b.randomChance=(n,d)=>n>=d;b.randomizer=x=>x;return[b.p1.active[0],b.p2.active[0]];}
 function hit(p,t,extra={}){const m=b.dex.getActiveMove('watergun');Object.assign(m,{accuracy:true,willCrit:false,basePower:5,secondaries:undefined},extra);b.actions.runMove(m,t,t.getLocOf(p));}
 function messages(){return b.log.filter(x=>x.includes('draws in hostility'));}
 it('boosts after the whole multihit move, once, with the exact Chandelure message',()=>{const[p,t]=setup();const during=[];b.onEvent('DamagingHit',b.format,(d,target)=>{if(target===p)during.push(p.boosts.spa);});hit(p,t,{multihit:3});assert.deepEqual(during,[0,0,0]);assert.equal(p.boosts.spa,1);assert(p.m.maliceWellUsed);assert.deepEqual(messages(),['|-message|Through its otherworldly eye, Chandelure draws in hostility and turns it into power!']);hit(p,t);assert.equal(p.boosts.spa,1);assert.equal(messages().length,1);});
 for(const mode of ['protect','miss','immune'])it('counts executed targeting through '+mode,()=>{const[p,t]=setup();if(mode==='protect')p.addVolatile('protect');const hp=p.hp;hit(p,t,mode==='miss'?{accuracy:0}:mode==='immune'?{type:'Normal'}:{});assert.equal(p.hp,hp);assert.equal(p.boosts.spa,1);assert.equal(messages().length,1);});
 it('does not boost if a later multihit strike faints the holder',()=>{const[p,t]=setup();p.hp=10;hit(p,t,{multihit:3,damage:6});assert.equal(p.hp,0);assert.equal(messages().length,0);assert(!p.m.maliceWellUsed);});
 it('survives a complete Protect turn and resolves after the attacker',()=>{const[p]=setup();b.makeChoices('move protect','move watergun');assert.equal(p.boosts.spa,1);assert.equal(messages().length,1);});
 it('does not trigger from status, residual or a selected move prevented by sleep',()=>{const[p,t]=setup();b.damage(1,p,t,b.dex.conditions.get('brn'));b.makeChoices('move splash','move splash');assert.equal(p.boosts.spa,0);t.setStatus('slp');t.statusState.time=4;b.makeChoices('move splash','move watergun');assert.equal(p.boosts.spa,0);assert.equal(messages().length,0);});
 it('excludes an allied or self damaging move',()=>{const[p]=setup();hit(p,p,{type:'Fire',basePower:1});assert.equal(p.boosts.spa,0);assert(!p.m.maliceWellUsed);});
 it('retains spent use through ability replacements and suppression; Haze does not refresh it',()=>{const[p,t]=setup();hit(p,t);p.setAbility('No Ability');p.setAbility('Soul Cremation');p.addVolatile('gastroacid');p.removeVolatile('gastroacid');p.clearBoosts();hit(p,t);assert.equal(p.boosts.spa,0);assert.equal(messages().length,1);});
 it('suppression prevents the trigger without spending an unused entry',()=>{const[p,t]=setup();p.addVolatile('gastroacid');hit(p,t);assert.equal(p.boosts.spa,0);assert(!p.m.maliceWellUsed);p.removeVolatile('gastroacid');hit(p,t);assert.equal(p.boosts.spa,1);});
 it('actual switching resets the entry budget and normal boost stages',()=>{const[p,t]=setup();hit(p,t);b.makeChoices('switch 2','move splash');b.makeChoices('switch 2','move splash');assert.equal(p.boosts.spa,0);assert(!p.m.maliceWellUsed);hit(p,t);assert.equal(p.boosts.spa,1);assert.equal(messages().length,2);});
 it('spends the first activation at the stat cap without a false success message',()=>{const[p,t]=setup();p.boosts.spa=6;hit(p,t);assert(p.m.maliceWellUsed);assert.equal(messages().length,0);p.boosts.spa=0;hit(p,t);assert.equal(p.boosts.spa,0);});
 it('counts spread/multihit targeting once in FFA',()=>{const[p,t]=setup('Soul Cremation',true);hit(p,t,{target:'allAdjacentFoes',multihit:3});assert.equal(p.boosts.spa,1);assert.equal(messages().length,1);});
 it('uses the copied holder species in its message',()=>{const[p,t]=setup();t.setAbility('Malice Well');p.moveSlots[0]={...p.moveSlots[0],id:'watergun',move:'Water Gun'};hit(t,p);assert.equal(t.boosts.spa,1);assert(messages().some(x=>x.includes('Mew draws in hostility')));});
 it('does not duplicate Flame Body inside Soul Cremation',()=>{const[p,t]=setup();let calls=0;b.randomChance=(n,d)=>{if(n===3&&d===10)calls++;return false;};hit(p,t,{type:'Water',flags:{contact:1}});assert.equal(calls,1);assert(p.hasAbility('flamebody'));assert(p.hasAbility('malicewell'));});
 it('counts a delayed attack only when it arrives and finishes',()=>{const[p,t]=setup();t.moveSlots[0]={...t.moveSlots[0],id:'futuresight',move:'Future Sight'};b.makeChoices('move splash','move futuresight');assert.equal(p.boosts.spa,0);b.makeChoices('move splash','move splash');b.makeChoices('move splash','move splash');assert.equal(p.boosts.spa,1);assert.equal(messages().length,1);});
 it('excludes damaging moves from a doubles ally',()=>{const pset={species:'Chandelure',ability:'Soul Cremation',moves:['watergun']},ally={species:'Mew',ability:'No Ability',moves:['watergun']};b=common.createBattle({formatid:'gen9nofielddoublesbattle'},[[pset,ally],[ally,ally]]);b.makeChoices('team 12','team 12');const p=b.p1.active[0];hit(p,b.p1.active[1]);assert.equal(p.boosts.spa,0);assert(!p.m.maliceWellUsed);});
 it('real Skill Swap cycles and Haze do not refresh the spent entry',()=>{const[p,t]=setup();hit(p,t);t.moveSlots[0]={...t.moveSlots[0],id:'skillswap',move:'Skill Swap'};b.makeChoices('move haze','move skillswap');b.makeChoices('move splash','move skillswap');assert(p.hasAbility('malicewell'));assert(p.m.maliceWellUsed);t.moveSlots[0]={...t.moveSlots[0],id:'watergun',move:'Water Gun'};hit(p,t);assert.equal(p.boosts.spa,0);assert.equal(messages().length,1);});
});
