'use strict';
const assert=require('assert').strict,common=require('../../common'),{Dex}=require('../../../dist/sim');let battle;
function start(move='tackle',foe='seismictoss'){
 const reserve={species:'Mew',ability:'No Ability',moves:['splash']};
 battle=common.createBattle({formatid:'gen9nofieldsinglesgame'},[[{species:'Golisopod',ability:'Tactical Retreat',moves:[move]},reserve],[{species:'Mew',ability:'No Ability',moves:[foe]},reserve]]);
 if(battle.requestState==='teampreview')battle.makeChoices('team 12','team 12');
 battle.field.terrain='';battle.randomChance=(n,d)=>n>=d;battle.randomizer=x=>x;
 const p=battle.p1.active[0],t=battle.p2.active[0];p.maxhp=p.baseMaxhp=400;p.hp=250;t.hp=t.maxhp=t.baseMaxhp=4000;return[p,t];
}
function use(p,t,id,patch={}){battle.clearActiveMove();const m=battle.dex.getActiveMove(id);Object.assign(m,{accuracy:true,willCrit:false,secondaries:null},patch);battle.actions.useMove(m,p,{target:t});battle.clearActiveMove();}
describe('Approved Tactical Retreat and Rain Courier',()=>{
 afterEach(()=>{battle?.destroy();battle=null;});
 it('replaces only approved slots and exposes calculator metadata',()=>{assert.deepEqual(Dex.species.get('golisopod').abilities,{0:'Tactical Retreat',1:'Inner Focus',H:'Shell Armor'});assert.deepEqual(Dex.species.get('pelipper').abilities,{0:'Accumulation',1:'Drizzle',H:'Rain Courier'});assert.notEqual(Dex.species.get('golisopodmega').abilities[0],'Tactical Retreat');const m=require('../../../dist/sim/custom-calculator').calculatorMetadata();for(const id of ['golisopod','pelipper'])assert.deepEqual(m.species.find(s=>s.name===Dex.species.get(id).name).abilities,Dex.species.get(id).abilities);});
 it('lets the selected slower attack finish once without modifying priority, then retreats',()=>{const[p,t]=start();battle.makeChoices('move 1','move 1');assert.equal(battle.requestState,'switch');assert.equal(p.hp,150);assert(t.hp<4000);assert.equal(battle.log.filter(l=>l.startsWith('|move|p1a:')&&l.includes('|Tackle|')).length,1);assert(!p.abilityState.tacticalRetreatPending);assert.equal(battle.dex.moves.get('tackle').priority,0);});
 it('retreats normally before a selected status move',()=>{const[p,t]=start('splash');battle.makeChoices('move 1','move 1');assert.equal(battle.requestState,'switch');assert.equal(t.hp,4000);assert(!battle.log.some(l=>l.startsWith('|move|p1a:')));assert(!p.abilityState.tacticalRetreatPending);});
 it('retreats normally when its attack already acted',()=>{const[p]=start('quickattack');battle.makeChoices('move 1','move 1');assert.equal(battle.requestState,'switch');assert(!p.abilityState.tacticalRetreatPending);assert.equal(battle.log.filter(l=>l.startsWith('|move|p1a:')).length,1);});
 it('still retreats after a queued attack is prevented by paralysis',()=>{const[p,t]=start();p.setStatus('par');battle.randomChance=()=>true;battle.makeChoices('move 1','move 1');assert.equal(battle.requestState,'switch');assert.equal(t.hp,4000);assert(battle.log.some(l=>l.includes('|cant|p1a:')&&l.includes('|par')));assert(!p.abilityState.tacticalRetreatPending);});
 it('never retreats when fainted or when no threshold was crossed',()=>{for(const hp of [50,150,350]){const[p]=start();p.hp=hp;battle.makeChoices('move 1','move 1');assert(!battle.log.some(l=>l.includes('ability: Tactical Retreat')));assert(!p.abilityState.tacticalRetreatPending);battle.destroy();battle=null;}});
 it('respects lack of reserves and leaves another Pokemon pivot flag intact',()=>{const[p,t]=start();t.switchFlag='uturn';battle.runEvent('EmergencyExit',p);assert.equal(t.switchFlag,'uturn');assert.equal(p.switchFlag,true);p.switchFlag=false;p.side.pokemon[1].fainted=true;p.side.pokemon[1].hp=0;battle.runEvent('EmergencyExit',p);assert(!p.switchFlag);});
 it('clears deferred state on ability loss and switch-out',()=>{const[p]=start();p.abilityState.tacticalRetreatPending=true;p.setAbility('No Ability');assert(!p.abilityState.tacticalRetreatPending);p.setAbility('Tactical Retreat');p.abilityState.tacticalRetreatPending=true;battle.singleEvent('SwitchOut',p.getAbility(),p.abilityState,p);assert(!p.abilityState.tacticalRetreatPending);});
 it('does not interrupt a multi-hit attack',()=>{const[p,t]=start('tackle','doublehit');p.hp=250;const move=battle.dex.getActiveMove('doublehit');Object.assign(move,{accuracy:true,damage:60,multihit:2,willCrit:false,secondaries:null});battle.queue.clear();battle.queue.addChoice({choice:'move',pokemon:p,moveid:'tackle',targetLoc:1});battle.actions.useMove(move,t,{target:p});assert.equal(p.hp,130);assert(p.abilityState.tacticalRetreatPending);assert(!p.switchFlag);assert(battle.log.some(l=>l.includes('|-hitcount|')&&l.endsWith('|2')));});
 it('does not heal or cleanse stages when retreat triggers',()=>{const[p]=start();p.boosts.def=-2;battle.makeChoices('move 1','move 1');assert.equal(p.hp,150);assert.equal(p.boosts.def,-2);});

 it('known sleep and flinch use the normal retreat opportunity without spending an action',()=>{for(const mode of ['sleep','flinch']){const[p]=start();if(mode==='sleep'){p.setStatus('slp');p.statusState.time=3;}else p.addVolatile('flinch');battle.makeChoices('move 1','move 1');assert.equal(battle.requestState,'switch');assert(!battle.log.some(l=>l.startsWith('|cant|p1a:')));assert(!p.abilityState.tacticalRetreatPending);battle.destroy();battle=null;}});
 it('a missed queued attack still retreats at its action boundary',()=>{const[p,t]=start('fissure');t.setType('Flying');battle.makeChoices('move 1','move 1');assert.equal(battle.requestState,'switch');assert.equal(t.hp,4000);assert(!p.abilityState.tacticalRetreatPending);});
 it('cancelled queued action resolves pending retreat at the next boundary',()=>{const[p,t]=start();battle.queue.clear();battle.queue.addChoice({choice:'move',pokemon:p,moveid:'tackle',targetLoc:1});battle.runEvent('EmergencyExit',p);assert(p.abilityState.tacticalRetreatPending);battle.queue.cancelMove(p);battle.runAction({choice:'event',event:'Update',pokemon:t});assert.equal(p.switchFlag,true);assert(!p.abilityState.tacticalRetreatPending);});
 it('suppression clears pending retreat and fainting never activates it',()=>{const[p,t]=start();p.abilityState.tacticalRetreatPending=true;p.addVolatile('gastroacid',t);battle.runAction({choice:'event',event:'Update',pokemon:t});assert(!p.abilityState.tacticalRetreatPending);assert(!p.switchFlag);p.removeVolatile('gastroacid');p.hp=0;battle.runEvent('EmergencyExit',p);assert(!p.switchFlag);});
 function courier(){const[p,t]=start();p.setAbility('Rain Courier');return[p,t];}
 const hazards=['spikes','toxicspikes','stealthrock','stickyweb','gmaxsteelsurge'];
 function lay(p){for(const h of hazards)p.side.addSideCondition(h,p);}
 it('clears all own hazards only on successful Tailwind establishment, once per entry',()=>{const[p,t]=courier();lay(p);lay(t);use(p,p,'tailwind');assert(p.side.sideConditions.tailwind);assert(p.volatiles.raincourierspent);for(const h of hazards){assert(!p.side.sideConditions[h],h);assert(t.side.sideConditions[h],h);}lay(p);p.side.removeSideCondition('tailwind');use(p,p,'tailwind');assert(p.side.sideConditions.spikes);});
 it('failed active Tailwind preserves hazards and does not spend its use',()=>{const[p]=courier();p.side.addSideCondition('tailwind',p);lay(p);use(p,p,'tailwind');assert(!p.volatiles.raincourierspent);assert(p.side.sideConditions.spikes);p.side.removeSideCondition('tailwind');use(p,p,'tailwind');assert(!p.side.sideConditions.spikes);});
 it('retains Rain Dish healing and suppression without duplicate healing',()=>{const[p,t]=courier();battle.field.setWeather('raindance',p);const hp=p.hp;battle.runEvent('Weather',p,null,battle.dex.conditions.get('raindance'));assert.equal(p.hp,hp+25);p.addVolatile('gastroacid',t);const before=p.hp;battle.runEvent('Weather',p,null,battle.dex.conditions.get('raindance'));assert.equal(p.hp,before);lay(p);use(p,p,'tailwind');assert(p.side.sideConditions.spikes);assert(!p.volatiles.raincourierspent);});
 it('resets the Tailwind use on a real switch',()=>{const[p]=courier();lay(p);use(p,p,'tailwind');assert(p.volatiles.raincourierspent);battle.makeChoices('switch 2','move 1');assert(!p.volatiles.raincourierspent);});
});
