'use strict';
const assert=require('assert').strict,common=require('../../common');
describe('Savage Resolve',()=>{
 let b;afterEach(()=>b?.destroy());
 function setup(item=''){const p={species:'Ursaring',ability:'Savage Resolve',item,moves:['tackle','splash']},t={species:'Mew',ability:'No Ability',moves:['watergun','splash']};b=common.createBattle({formatid:'gen9nofieldsinglesgame'},[[p,p],[t,t]]);b.makeChoices('team 12','team 12');b.randomChance=(n,d)=>n>=d;b.randomizer=x=>x;return[b.p1.active[0],b.p2.active[0]];}
 function hit(p,t,extra={}){const m=b.dex.getActiveMove('watergun');Object.assign(m,{accuracy:true,willCrit:false,basePower:5,secondaries:undefined},extra);b.actions.runMove(m,t,t.getLocOf(p));}
 it('boosts only after the whole multihit attack, once per entry',()=>{const[p,t]=setup();p.setStatus('brn');const during=[];b.onEvent('DamagingHit',b.format,()=>during.push(p.boosts.spe));hit(p,t,{multihit:3});assert.deepEqual(during,[0,0,0]);assert.equal(p.boosts.spe,1);hit(p,t);assert.equal(p.boosts.spe,1);});
 it('does not boost if a later hit faints it',()=>{const[p,t]=setup();p.setStatus('brn');p.hp=10;hit(p,t,{multihit:3,damage:6});assert.equal(p.hp,0);assert.equal(p.boosts.spe,0);});
 it('does not retroactively qualify status inflicted by the hit',()=>{const[p,t]=setup();hit(p,t,{secondaries:[{chance:100,status:'brn'}]});assert.equal(p.status,'brn');assert.equal(p.boosts.spe,0);hit(p,t);assert.equal(p.boosts.spe,1);});
 for(const mode of ['healthy','protect','miss','immune','substitute','delayed','self','residual','suppressed'])it('excludes '+mode,()=>{const[p,t]=setup();if(mode!=='healthy')p.setStatus('brn');if(mode==='protect')p.addVolatile('protect');if(mode==='substitute')p.addVolatile('substitute');if(mode==='suppressed')p.addVolatile('gastroacid');if(mode==='residual')b.damage(5,p,t,b.dex.conditions.get('brn'));else hit(p,mode==='self'?p:t,mode==='miss'?{accuracy:0}:mode==='immune'?{type:'Ghost'}:mode==='delayed'?{flags:{futuremove:1}}:{});assert.equal(p.boosts.spe,0);});
 it('does not refresh through ability replacement, suppression or Haze',()=>{const[p,t]=setup();p.setStatus('brn');hit(p,t);p.clearBoosts();p.setAbility('No Ability');p.setAbility('Savage Resolve');p.addVolatile('gastroacid');p.removeVolatile('gastroacid');hit(p,t);assert.equal(p.boosts.spe,0);assert(p.m.savageResolveUsed);});
 it('resets on actual switch-in',()=>{const[p,t]=setup();p.setStatus('brn');hit(p,t);b.makeChoices('switch 2','move splash');b.makeChoices('switch 2','move splash');assert(!p.m.savageResolveUsed);hit(p,t);assert.equal(p.boosts.spe,1);});
 it('preserves Guts identity, Attack multiplier and burn exemption',()=>{const[p,t]=setup();assert(p.hasAbility('guts'));const atk=p.getStat('atk');p.setStatus('brn');assert.equal(p.getStat('atk'),Math.floor(atk*1.5));const m=b.dex.getActiveMove('tackle');m.willCrit=false;const burned=b.actions.getDamage(p,t,m);p.cureStatus();const healthy=b.actions.getDamage(p,t,m);assert(burned>healthy*1.4);});
 it('keeps Eviolite defenses and Flame Orb activation',()=>{const[p]=setup('Eviolite');assert(p.species.nfe);assert.equal(p.getStat('def'),Math.floor(p.storedStats.def*1.5));assert.equal(p.getStat('spd'),Math.floor(p.storedStats.spd*1.5));p.setItem('Flame Orb');b.makeChoices('move splash','move splash');assert.equal(p.status,'brn');assert.equal(p.boosts.spe,0);});
 it('consumes at the Speed cap and does not remove paralysis',()=>{const[p,t]=setup();p.setStatus('par');p.boosts.spe=6;hit(p,t);assert(p.m.savageResolveUsed);assert.equal(p.status,'par');p.clearBoosts();hit(p,t);assert.equal(p.boosts.spe,0);});
 it('excludes allied damage in doubles',()=>{const p={species:'Ursaring',ability:'Savage Resolve',moves:['splash']},t={species:'Mew',ability:'No Ability',moves:['watergun']};b=common.createBattle({formatid:'gen9nofielddoublesbattle'},[[p,t],[t,t]]);b.makeChoices('team 12','team 12');const holder=b.p1.active[0];holder.setStatus('brn');hit(holder,b.p1.active[1]);assert.equal(holder.boosts.spe,0);});
});
