'use strict';
const assert=require('assert').strict,common=require('../../common');
describe('Spent Force',()=>{
 let b;afterEach(()=>b?.destroy());
 function setup(ffa=false){let p={species:'Slaking',ability:'Spent Force',moves:['tackle','splash']},t={species:'Mew',ability:'No Ability',moves:['splash']};let teams=ffa?[[p,p],[t,t],[t,t],[t,t]]:[[p,p],[t,t]];b=common.createBattle({formatid:ffa?'gen9freeforall4pmistyfieldadrienn':'gen9nofieldsinglesgame'},teams);b.makeChoices(...teams.map(()=>'team 12'));b.randomChance=(n,d)=>n>=d;b.randomizer=x=>x;return[b.p1.active[0],b.p2.active[0]];}
 function attack(p,t,extra={},name='tackle'){let m=b.dex.getActiveMove(name);Object.assign(m,{accuracy:true,willCrit:false,basePower:10,secondaries:undefined},extra);b.actions.runMove(m,p,p.getLocOf(t));}
 function damage(p,t,name='tackle'){let m=b.dex.getActiveMove(name);m.willCrit=false;return b.actions.getDamage(p,t,m);}
 it('preserves stats and existing slots with a third choice',()=>{let[p]=setup();assert.deepEqual(p.species.baseStats,{hp:150,atk:160,def:100,spa:95,spd:65,spe:100});assert.deepEqual(p.species.abilities,{0:'Truant',1:'Slow Start',H:'Spent Force'});});
 it('finishes every hit at full power before halving both damage categories and Speed',()=>{let[p,t]=setup(),spe=p.getStat('spe'),phys=damage(p,t),special=damage(p,t,'watergun'),hits=[];b.onEvent('DamagingHit',b.format,d=>hits.push(d));attack(p,t,{multihit:3});assert.equal(hits.length,3);assert(hits.every(x=>x===hits[0]));assert.equal(p.getStat('spe'),Math.floor(spe/2));assert(Math.abs(damage(p,t)*2-phys)<=2);assert(Math.abs(damage(p,t,'watergun')*2-special)<=2);});
 it('keeps the whole initial FFA spread attack unpenalized',()=>{let[p,t]=setup(true),during=[];b.onEvent('DamagingHit',b.format,()=>during.push(p.m.spentForceUntil));attack(p,t,{target:'allAdjacentFoes'});assert.equal(during.length,3);assert(during.every(x=>x===undefined));assert.equal(p.m.spentForceUntil,b.turn+1);});
 for(let mode of ['miss','protect','immune'])it('counts '+mode,()=>{let[p,t]=setup();if(mode==='protect')t.addVolatile('protect');if(mode==='immune')t.setType('Ghost');attack(p,t,mode==='miss'?{accuracy:0}:{});assert.equal(p.m.spentForceUntil,b.turn+1);});
 it('refreshes on consecutive attacks and expires after a status turn',()=>{let[p,t]=setup(),spe=p.getStat('spe');attack(p,t);b.turn++;attack(p,t);assert.equal(p.m.spentForceUntil,b.turn+1);b.turn++;attack(p,t,{},'splash');assert.equal(p.getStat('spe'),Math.floor(spe/2));b.turn++;assert.equal(p.getStat('spe'),spe);});
 it('does not count a sleeping user whose move never executes',()=>{let[p,t]=setup();p.setStatus('slp');p.statusState.time=4;attack(p,t);assert.equal(p.m.spentForceUntil,undefined);});
 it('keeps a fatigue timer through suppression and ability changes',()=>{let[p,t]=setup(),spe=p.getStat('spe');attack(p,t);let until=p.m.spentForceUntil;p.addVolatile('gastroacid');assert.equal(p.getStat('spe'),spe);p.removeVolatile('gastroacid');assert.equal(p.getStat('spe'),Math.floor(spe/2));p.setAbility('No Ability');assert.equal(p.getStat('spe'),spe);p.setAbility('Spent Force');assert.equal(p.m.spentForceUntil,until);assert.equal(p.getStat('spe'),Math.floor(spe/2));});
 it('clears fatigue when it actually switches back in',()=>{let[p,t]=setup(),spe=p.getStat('spe');attack(p,t);b.makeChoices('switch 2','move splash');b.makeChoices('switch 2','move splash');assert.equal(p.m.spentForceUntil,undefined);assert.equal(p.getStat('spe'),spe);});
 it('counts Struggle but preserves fixed damage semantics',()=>{let[p,t]=setup();attack(p,t,{},'struggle');assert.equal(p.m.spentForceUntil,b.turn+1);assert.equal(damage(p,t,'seismictoss'),p.level);});
});
