// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts
/*
If you want to add custom formats, create a file in this folder named: "custom-formats.ts"

Paste the following code into the file and add your desired formats and their sections between the brackets:
--------------------------------------------------------------------------------
// Note: This is the list of formats
// The rules that formats use are stored in data/rulesets.ts

export const Formats: FormatList = [
];
--------------------------------------------------------------------------------

If you specify a section that already exists, your format will be added to the bottom of that section.
New sections will be added to the bottom of the specified column.
The column value will be ignored for repeat sections.
*/

export const Formats: FormatList = [

	//All Gen Reborn
	///////////////////////////////////////////////////////////////////
	{
		section: "AllGen Singles",
		column: 1,
	},
	{
		name: "[Gen 9] Random Field",
		mod: 'gen9',
		terrain: 'randomterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Misty Field(Adrienn)",
		mod: 'gen9',
		terrain: 'adriennterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Elemental",
	},
	{
		name: "[Gen 9] Burning Field",
		mod: 'gen9',
		terrain: 'burningterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Cold Eclipse Field",
		mod: 'gen9',
		terrain: 'coldeclipseterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Corrosive Mist Field",
		mod: 'gen9',
		terrain: 'corrosivemistterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Dragon's Den",
		mod: 'gen9',
		terrain: 'dragonsdenterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Electric Field",
		mod: 'gen9',
		terrain: 'electricterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Grassy Field",
		mod: 'gen9',
		terrain: 'grassyterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Icy Field",
		mod: 'gen9',
		terrain: 'icyterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Misty Field",
		mod: 'gen9',
		terrain: 'mistyterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Murkwater Surface",
		mod: 'gen9',
		terrain: 'murkwaterterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Underwater",
		mod: 'gen9',
		terrain: 'underwaterterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Water Surface",
		mod: 'gen9',
		terrain: 'watersurfaceterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Magical",
	},
	{
		name: "[Gen 9] Bewitched Woods",
		mod: 'gen9',
		terrain: 'bewitchedwoodsterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Crystal Cavern",
		mod: 'gen9',
		terrain: 'crystalcavernterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Dark Crystal Cavern",
		mod: 'gen9',
		terrain: 'darkcrystalcavernterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Fairy Tale Field",
		mod: 'gen9',
		terrain: 'fairytaleterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Inverse Field",
		mod: 'gen9',
		terrain: 'inverseterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Haunted Field",
		mod: 'gen9',
		terrain: 'hauntedterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Holy Field",
		mod: 'gen9',
		terrain: 'holyterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] New World",
		mod: 'gen9',
		terrain: 'newworldterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Psychic Field",
		mod: 'gen9',
		terrain: 'psychicterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Rainbow Field",
		mod: 'gen9',
		terrain: 'rainbowterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Starlight Arena",
		mod: 'gen9',
		terrain: 'starlightarenaterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Synthetic",
	},
	{
		name: "[Gen 9] Big Top Arena",
		mod: 'gen9',
		terrain: 'bigtopterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Factory Field",
		mod: 'gen9',
		terrain: 'factoryterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Glitch Field",
		mod: 'gen9',
		terrain: 'glitchterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Mirror Arena",
		mod: 'gen9',
		terrain: 'mirrorarenaterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Moves Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Short-Circuit Field",
		mod: 'gen9',
		terrain: 'shortcircuitterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Telluric",
	},
	{
		name: "[Gen 9] Ashen Beach",
		mod: 'gen9',
		terrain: 'ashenbeachterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Cave Field",
		mod: 'gen9',
		terrain: 'caveterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Corrosive Field",
		mod: 'gen9',
		terrain: 'corrosiveterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Desert Field",
		mod: 'gen9',
		terrain: 'desertterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Forest Field",
		mod: 'gen9',
		terrain: 'forestterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Rocky Field",
		mod: 'gen9',
		terrain: 'rockyterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Super-Heated Field",
		mod: 'gen9',
		terrain: 'superheatedterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Swamp Field",
		mod: 'gen9',
		terrain: 'swampterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Wasteland Field",
		mod: 'gen9',
		terrain: 'wastelandterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},



	//All Gen Doubles
	///////////////////////////////////////////////////////////////////////////////////////////////////

	{
		section: "AllGen Doubles",
		column: 2,
	},
	{
		name: "[Gen 9] Doubles Random Field",
		mod: 'gen9',
		terrain: 'randomterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Misty Field (Adrienn)",
		mod: 'gen9',
		terrain: 'adriennterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Elemental",
	},
	{
		name: "[Gen 9] Doubles Burning Field",
		mod: 'gen9',
		terrain: 'burningterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Cold Eclipse Field",
		mod: 'gen9',
		terrain: 'coldeclipseterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Corrosive Mist Field",
		mod: 'gen9',
		terrain: 'corrosivemistterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Dragon's Den",
		mod: 'gen9',
		terrain: 'dragonsdenterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Electric Field",
		mod: 'gen9',
		terrain: 'electricterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Grassy Field",
		mod: 'gen9',
		terrain: 'grassyterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Sleep Clause Mod', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Icy Field",
		mod: 'gen9',
		terrain: 'icyterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Misty Field",
		mod: 'gen9',
		terrain: 'mistyterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Murkwater Surface",
		mod: 'gen9',
		terrain: 'murkwatersurfaceterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Underwater",
		mod: 'gen9',
		terrain: 'underwaterterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Water Surface",
		mod: 'gen9',
		terrain: 'watersurfaceterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Magical"
	},
	{
		name: "[Gen 9] Doubles Bewitched Woods",
		mod: 'gen9',
		terrain: 'bewitchedwoodsterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Crystal Cavern",
		mod: 'gen9',
		terrain: 'crystalcavernterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Dark Crystal Cavern",
		mod: 'gen9',
		terrain: 'darkcrystalcavernterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Fairy Tale Field",
		mod: 'gen9',
		terrain: 'fairytaleterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Holy Field",
		mod: 'gen9',
		terrain: 'holyterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Haunted Field",
		mod: 'gen9',
		terrain: 'hauntedterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Inverse Field",
		mod: 'gen9',
		terrain: 'inverseterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles New World",
		mod: 'gen9',
		terrain: 'newworldterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Psychic Field",
		mod: 'gen9',
		terrain: 'psychicterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Rainbow Field",
		mod: 'gen9',
		terrain: 'rainbowterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Starlight Arena",
		mod: 'gen9',
		terrain: 'starlightarenaterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Synthetic",
	},
	{
		name: "[Gen 9] Doubles Big Top Arena",
		mod: 'gen9',
		terrain: 'bigtopterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Sleep Clause Mod', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Chess Board",
		mod: 'gen9',
		terrain: 'chessboardterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Picked Team Size = 6', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Factory Field",
		mod: 'gen9',
		terrain: 'factoryterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Glitch Field",
		mod: 'gen9',
		terrain: 'glitchterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Mirror Arena",
		mod: 'gen9',
		terrain: 'mirrorarenaterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Moves Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Short-Circuit Field",
		mod: 'gen9',
		terrain: 'shortcircuitterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		subsection: "Telluric",
	},
	{
		name: "[Gen 9] Doubles Ashen Beach",
		mod: 'gen9',
		terrain: 'ashenbeachterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},	
	{
		name: "[Gen 9] Doubles Cave",
		mod: 'gen9',
		terrain: 'caveterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Corrosive Field",
		mod: 'gen9',
		terrain: 'corrosiveterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Desert Field",
		mod: 'gen9',
		terrain: 'desertterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Forest Field",
		mod: 'gen9',
		terrain: 'forestterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Mountain",
		mod: 'gen9',
		terrain: 'mountainterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Rocky Field",
		mod: 'gen9',
		terrain: 'rockyterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Snowy Mountain",
		mod: 'gen9',
		terrain: 'snowymountainterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Super-Heated Field",
		mod: 'gen9',
		terrain: 'superheatedterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Swamp Field",
		mod: 'gen9',
		terrain: 'swampterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] Doubles Wasteland Field",
		mod: 'gen9',
		terrain: 'wastelandterrain',
		gameType: "doubles",
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},

	{
		section: "AllGen 6/4 Doubles",
		column: 3,
	},
	{
		name: "[Gen 9] 6/4 Doubles Random Field",
		mod: 'gen9',
		terrain: 'randomterrain',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Evasion Clause', 'Cancel Mod', 'Sleep Clause Mod', 'Max Team Size = 6', 'Picked Team Size = 4', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] 6/4 Doubles No Field",
		mod: 'gen9',
		gameType: 'doubles',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Picked Team Size = 4', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	
	{
		section: "[Gen 9] 6/3 Singles",
		column: 5
	},
	{
		name: "[Gen 9] 6/3 Random Field",
		mod: 'gen9',
		terrain: 'randomterrain',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Picked Team Size = 3', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] 6/3 No Field",
		mod: 'gen9',
		searchShow: true,
		debug: true,
		battle: { trunc: Math.trunc },
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Picked Team Size = 3', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},

	{
		section: "AllGen No Field Battles",
		column: 4,
	},
	{
		name: "[Gen 9] No Field Singles Game",

		mod: 'gen9',
		battle: {trunc: Math.trunc},
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] No Field Doubles Battle",

		mod: 'gen9',
		gameType: 'doubles',
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
	{
		name: "[Gen 9] No Field 6/4 Doubles Battle",

		mod: 'gen9',
		gameType: 'doubles',
		ruleset: ['Team Preview', 'Sleep Clause Mod', 'Evasion Clause', 'Cancel Mod', 'Max Team Size = 6', 'Picked Team Size = 4', 'Max Move Count = 4', 'Max Level = 100', 'Default Level = 100', '+Unobtainable', '+Past'],
	},
];
