/* eslint-disable @stylistic/max-len */
import {toID} from '../sim/dex-data';
export const Conditions: import('../sim/dex-conditions').ConditionDataTable = {
	ghostresistance: {
		name: 'Ghost Resistance',
		onSourceModifyDamage(damage, source, target, move) {
			if (move.category !== 'Status' && this.movehasType(move, 'Ghost')) {
				return this.chainModify(0.5);
			}
		},
	},
	resuscitationpending: {
		name: 'Resuscitation Pending',
		noCopy: true,
		onDamage() {
			return false;
		},
		onTryHit(target, source) {
			if (target !== source) return null;
		},
		onBeforeMove(pokemon) {
			this.add('cant', pokemon, 'ability: Parasitism');
			return false;
		},
		onResidualOrder: 29,
		onResidual(pokemon) {
			if (!pokemon.hp || pokemon.baseSpecies.id !== 'parasect') {
				pokemon.removeVolatile('resuscitationpending');
				return;
			}

			// Treat the revival like a fresh battle state without restoring PP or items.
			pokemon.cureStatus();
			pokemon.clearVolatile();
			this.add('-clearboost', pokemon);
			pokemon.formeChange('Parasect-Parasite', this.dex.abilities.get('parasitism'), true);
			this.add('-message', `${pokemon.name} was fully revived as Parasect-Parasite!`);
			this.heal(pokemon.maxhp, pokemon, pokemon, this.dex.abilities.get('resuscitation'));
		},
	},
	powerofalchemycore: {
		name: 'Power of Alchemy Core',
		onImmunity(type, pokemon) {
			return this.dex.abilities.get('selfsufficient').onImmunity?.call(this, type, pokemon);
		},
		onResidual(pokemon) {
			this.dex.abilities.get('selfsufficient').onResidual?.call(this, pokemon);
		},
		onSwitchOut(pokemon) {
			this.dex.abilities.get('regenerator').onSwitchOut?.call(this, pokemon);
		},
	},
	parentalbondmotherguard: {
		name: 'Mother Guard',
		onStart(pokemon) {
			this.add('-start', pokemon, 'Mother Guard');
		},
		onDamage(damage, target, source, effect) {
			if (effect.effectType !== 'Move') return false;
		},
	},
	shadowforceguard: {
		name: 'Shadow Force Guard',
		duration: 2,
		onStart(pokemon) {
			this.add('-start', pokemon, 'Shadow Force Guard');
		},
		onDamage(damage, target, source, effect) {
			return this.modify(damage, 0.75);
		},
		onEnd(pokemon) {
			this.add('-end', pokemon, 'Shadow Force Guard');
		},
	},
	stellarhealing: {
		name: 'Stellar Healing',
		onResidualOrder: 9,
		onResidual(pokemon) {
			if (pokemon.terastallized === 'Stellar') {
				this.heal(pokemon.baseMaxhp / 16, pokemon, pokemon);
			}
		},
	},
	gmaxhealing: {
		name: 'G-Max Healing',
	},
	illusioncopy: {
		name: 'Illusion Copy',
		onModifyMove(move, pokemon) {
			if (pokemon.illusion && pokemon.illusion.getTypes().some(type => this.movehasType(move, type))) {
				move.forceSTAB = true;
			}
		},
		onDamagingHit(damage, target, source, move) {
			if (target.illusion) target.removeVolatile('illusioncopy');
		},
		onEnd(pokemon) {
			const originalAbility = this.effectState.originalAbility;
			if (originalAbility && pokemon.ability !== originalAbility) {
				const copiedAbility = pokemon.getAbility();
				this.singleEvent('End', copiedAbility, pokemon.abilityState, pokemon, pokemon);
				pokemon.ability = originalAbility;
				pokemon.abilityState = this.initEffectState({ id: originalAbility, target: pokemon });
			}
			if (pokemon.illusion && !pokemon.beingCalledBack) {
				this.debug('illusion cleared');
				pokemon.illusion = null;
				const details = pokemon.getUpdatedDetails();
				this.add('replace', pokemon, details);
				this.add('-end', pokemon, 'Illusion');
				if (this.ruleTable.has('illusionlevelmod')) {
					this.hint("Illusion Level Mod is active, so this Pokemon's true level was hidden.", true);
				}
			}
		},
	},
	brn: {
		name: 'brn',
		effectType: 'Status',
		onStart(target, source, sourceEffect) {
			if (sourceEffect && sourceEffect.id === 'flameorb') {
				this.add('-status', target, 'brn', '[from] item: Flame Orb');
			} else if (sourceEffect && sourceEffect.effectType === 'Ability') {
				this.add('-status', target, 'brn', '[from] ability: ' + sourceEffect.name, `[of] ${source}`);
			} else {
				this.add('-status', target, 'brn');
			}
		},
		// Damage reduction is handled directly in the sim/battle.js damage function
		onResidualOrder: 10,
		onResidual(pokemon) {
			let damageDivisor = 16;
			switch (this.field.terrain) {
			case 'icyterrain':
				damageDivisor = 32;
				break;
			case 'volcanicterrain':
				damageDivisor = 8;
				break;
			default:
				break;
			}
			const burnDamage = pokemon.baseMaxhp / damageDivisor;
			if (pokemon.hasAbility('sinisterblaze')) {
				this.heal(burnDamage, pokemon, pokemon, this.dex.abilities.get('sinisterblaze'));
				for (const foe of pokemon.foes()) {
					if (!foe.fainted && foe.hp) {
						// This damage is generated by Sinister Blaze and cannot heal it back.
						this.damage(burnDamage, foe, pokemon, this.dex.abilities.get('sinisterblaze'));
					}
				}
				return;
			}
			const damage = this.damage(burnDamage, pokemon, pokemon, this.effect);
			if (typeof damage === 'number' && damage > 0) {
				for (const foe of pokemon.foes()) {
					if (!foe.fainted && foe.hp && foe.hasAbility('sinisterblaze')) {
						this.heal(damage, foe, pokemon, this.dex.abilities.get('sinisterblaze'));
					}
				}
			}
		},
	},
	par: {
		name: 'par',
		effectType: 'Status',
		onStart(target, source, sourceEffect) {
			if (sourceEffect && sourceEffect.effectType === 'Ability') {
				this.add('-status', target, 'par', '[from] ability: ' + sourceEffect.name, `[of] ${source}`);
			} else {
				this.add('-status', target, 'par');
			}
		},
		onModifySpePriority: -101,
		onModifySpe(spe, pokemon) {
			// Paralysis occurs after all other Speed modifiers, so evaluate all modifiers up to this point first
			spe = this.finalModify(spe);
			if (!pokemon.hasAbility('quickfeet')) {
				spe = Math.floor(spe * 50 / 100);
			}
			return spe;
		},
		onBeforeMovePriority: 1,
		onBeforeMove(pokemon) {
			if (this.randomChance(1, 4)) {
				this.add('cant', pokemon, 'par');
				return false;
			}
		},
	},
	slp: {
		name: 'slp',
		effectType: 'Status',
		onStart(target, source, sourceEffect) {
			if (sourceEffect && sourceEffect.effectType === 'Ability') {
				this.add('-status', target, 'slp', '[from] ability: ' + sourceEffect.name, `[of] ${source}`);
			} else if (sourceEffect && sourceEffect.effectType === 'Move') {
				this.add('-status', target, 'slp', `[from] move: ${sourceEffect.name}`);
			} else {
				this.add('-status', target, 'slp');
			}
			// 1-3 turns
			this.effectState.startTime = this.random(2, 5);
			this.effectState.time = this.effectState.startTime;

			if (target.removeVolatile('nightmare')) {
				this.add('-end', target, 'Nightmare', '[silent]');
			}
		},
		onBeforeMovePriority: 10,
		onBeforeMove(pokemon, target, move) {
			if (pokemon.hasAbility('earlybird')) {
				pokemon.statusState.time--;
			}
			pokemon.statusState.time--;
			if (pokemon.statusState.time <= 0) {
				pokemon.cureStatus();
				this.heal(pokemon.baseMaxhp / 4, pokemon, pokemon);
				return;
			}
			this.add('cant', pokemon, 'slp');
			if (move.sleepUsable) {
				return;
			}
			return false;
		},

	},
	frz: {
		name: 'frz',
		effectType: 'Status',
		onStart(target, source, sourceEffect) {
			if (this.field.isTerrain('coldeclipseterrain') && target.hasType('Dragon')) return false;
			this.effectState.stage = 0;
			if (sourceEffect && sourceEffect.effectType === 'Ability') {
				this.add('-status', target, 'frz', '[from] ability: ' + sourceEffect.name, `[of] ${source}`);
			} else {
				this.add('-status', target, 'frz');
			}
			if (target.species.name === 'Shaymin-Sky' && target.baseSpecies.baseSpecies === 'Shaymin') {
				target.formeChange('Shaymin', this.effect, true);
			}
		},
		onModifyMove(move, pokemon) {
			if (move.flags['defrost']) {
				this.add('-curestatus', pokemon, 'frz', `[from] move: ${move}`);
				pokemon.clearStatus();
			}
		},
		onAfterMoveSecondary(target, source, move) {
			if (move.thawsTarget) {
				target.cureStatus();
			}
		},
		onDamagingHit(damage, target, source, move) {
			if (move.type === 'Fire' && move.category !== 'Status') {
				target.cureStatus();
			}
		},
		onResidual(pokemon) {
			if (this.field.isTerrain('coldeclipseterrain')) {
				if (this.effectState.stage < 15) {
					this.effectState.stage++;
				}
				this.damage(this.clampIntRange(pokemon.baseMaxhp / 16, 1) * this.effectState.stage);
			} else {
				this.damage(pokemon.baseMaxhp / 16);
			}
		},
	},
	psn: {
		name: 'psn',
		effectType: 'Status',
		onStart(target, source, sourceEffect) {
			if (sourceEffect && sourceEffect.effectType === 'Ability') {
				this.add('-status', target, 'psn', '[from] ability: ' + sourceEffect.name, `[of] ${source}`);
			} else {
				this.add('-status', target, 'psn');
			}
		},
		onResidualOrder: 9,
		onResidual(pokemon) {
			this.damage(pokemon.baseMaxhp / 8);
		},
	},
	tox: {
		name: 'tox',
		effectType: 'Status',
		onStart(target, source, sourceEffect) {
			this.effectState.stage = 0;
			if (sourceEffect && sourceEffect.id === 'toxicorb') {
				this.add('-status', target, 'tox', '[from] item: Toxic Orb');
			} else if (sourceEffect && sourceEffect.effectType === 'Ability') {
				this.add('-status', target, 'tox', '[from] ability: ' + sourceEffect.name, `[of] ${source}`);
			} else {
				this.add('-status', target, 'tox');
			}
		},
		onSwitchIn() {
			this.effectState.stage = 0;
		},
		onResidualOrder: 9,
		onResidual(pokemon) {
			if (this.effectState.stage < 15) {
				this.effectState.stage++;
			}
			this.damage(this.clampIntRange(pokemon.baseMaxhp / 16, 1) * this.effectState.stage);
		},
	},
	confusion: {
		name: 'confusion',
		// this is a volatile status
		onStart(target, source, sourceEffect) {
			if (sourceEffect?.id === 'lockedmove') {
				this.add('-start', target, 'confusion', '[fatigue]');
			} else if (sourceEffect?.effectType === 'Ability') {
				this.add('-start', target, 'confusion', '[from] ability: ' + sourceEffect.name, `[of] ${source}`);
			} else {
				this.add('-start', target, 'confusion');
			}
			const min = sourceEffect?.id === 'axekick' ? 3 : 2;
			this.effectState.time = this.random(min, 6);
		},
		onEnd(target) {
			this.add('-end', target, 'confusion');
		},
		onBeforeMovePriority: 3,
		onBeforeMove(pokemon) {
			pokemon.volatiles['confusion'].time--;
			if (!pokemon.volatiles['confusion'].time) {
				pokemon.removeVolatile('confusion');
				return;
			}
			this.add('-activate', pokemon, 'confusion');
			if (!this.randomChance(33, 100)) {
				return;
			}
			this.activeTarget = pokemon;
			const damage = this.actions.getConfusionDamage(pokemon, 40);
			if (typeof damage !== 'number') throw new Error("Confusion damage not dealt");
			const activeMove = { id: this.toID('confused'), effectType: 'Move', type: '???' };
			this.damage(damage, pokemon, pokemon, activeMove as ActiveMove);
			return false;
		},
	},
	flinch: {
		name: 'flinch',
		duration: 1,
		onBeforeMovePriority: 8,
		onBeforeMove(pokemon) {
			this.add('cant', pokemon, 'flinch');
			this.runEvent('Flinch', pokemon);
			return false;
		},
	},
	trapped: {
		name: 'trapped',
		noCopy: true,
		onTrapPokemon(pokemon) {
			pokemon.tryTrap();
		},
		onStart(target) {
			this.add('-activate', target, 'trapped');
		},
	},
	trapper: {
		name: 'trapper',
		noCopy: true,
	},
	partiallytrapped: {
		name: 'partiallytrapped',
		duration: 5,
		durationCallback(target, source, effect) {
			if (effect?.id === 'sandtomb' && this.field.isTerrain('desertterrain')) {
				return 5;
			}
			if (source?.hasItem('gripclaw')) return 8;
			return this.random(5, 7);
		},
		onStart(pokemon, source, effect) {
			this.add('-activate', pokemon, 'move: ' + this.effectState.sourceEffect, `[of] ${source}`);
			this.effectState.boundDivisor = source.hasItem('bindingband') ? 6 : 8;
			const moveBoosts: Record<string, readonly string[]> = {
				firespin: ['burningterrain', 'hauntedterrain'],
				whirlpool: ['watersurfaceterrain', 'underwaterterrain'],
				sandtomb: ['desertterrain'],
				magmastorm: ['dragonsdenterrain'],
				infestation: ['forestterrain'],
				thundercage: ['electricterrain'],
				snaptrap: ['grassyterrain'],
			};

			const terrains = moveBoosts[effect.id];

			if (terrains?.some(t => this.field.isTerrain(t))) {
				this.effectState.boundDivisor = 6;
			}
			if (this.field.isTerrain('ashenbeachterrain') && effect.id === 'sandtomb') {
				pokemon.addVolatile('sandtomb');
			}
		},
		onResidualOrder: 13,
		onResidual(pokemon) {
			const source = this.effectState.source;
			// G-Max Centiferno and G-Max Sandblast continue even after the user leaves the field
			const gmaxEffect = ['gmaxcentiferno', 'gmaxsandblast'].includes(this.effectState.sourceEffect.id);
			if (source && (!source.isActive || source.hp <= 0 || !source.activeTurns && !gmaxEffect)) {
				if (pokemon !== source || ['elementalseed', 'telluricseed'].includes(this.effectState.sourceEffect.id)) {
					delete pokemon.volatiles['partiallytrapped'];
					this.add('-end', pokemon, this.effectState.sourceEffect, '[partiallytrapped]', '[silent]');
					return;
				} else {
					return;
				}
			}
			this.damage(pokemon.baseMaxhp / this.effectState.boundDivisor);
		},
		onEnd(pokemon) {
			this.add('-end', pokemon, this.effectState.sourceEffect, '[partiallytrapped]');
		},
		onTrapPokemon(pokemon) {
			const gmaxEffect = ['gmaxcentiferno', 'gmaxsandblast'].includes(this.effectState.sourceEffect.id);
			if (this.effectState.source?.isActive || gmaxEffect) pokemon.tryTrap();
		},
	},
	lockedmove: {
		// Outrage, Thrash, Petal Dance...
		name: 'lockedmove',
		duration: 2,
		onResidual(target) {
			if (target.status === 'slp') {
				// don't lock, and bypass confusion for calming
				delete target.volatiles['lockedmove'];
			}
			this.effectState.trueDuration--;
		},
		onStart(target, source, effect) {
			this.effectState.trueDuration = this.random(2, 4);
			this.effectState.move = effect.id;
		},
		onRestart() {
			if (this.effectState.trueDuration >= 2) {
				this.effectState.duration = 2;
			}
		},
		onAfterMove(pokemon) {
			if (this.effectState.duration === 1) {
				pokemon.removeVolatile('lockedmove');
			}
		},
		onEnd(target) {
			if (this.effectState.trueDuration > 1) return;
			if (this.field.isTerrain(['burningterrain', 'volcanicterrain']) && this.effectState.move === 'ragingfury') return;
			target.addVolatile('confusion');
		},
		onLockMove(pokemon) {
			if (pokemon.volatiles['dynamax']) return;
			return this.effectState.move;
		},
	},
	twoturnmove: {
		// Skull Bash, SolarBeam, Sky Drop...
		name: 'twoturnmove',
		duration: 2,
		onStart(attacker, defender, effect) {
			// ("attacker" is the Pokemon using the two turn move and the Pokemon this condition is being applied to)
			this.effectState.move = effect.id;
			attacker.addVolatile(effect.id);
			// lastMoveTargetLoc is the location of the originally targeted slot before any redirection
			// note that this is not updated for moves called by other moves
			// i.e. if Dig is called by Metronome, lastMoveTargetLoc will still be the user's location
			let moveTargetLoc: number = attacker.lastMoveTargetLoc!;
			if (effect.sourceEffect && this.dex.moves.get(effect.id).target !== 'self') {
				// this move was called by another move such as Metronome
				// and needs a random target to be determined this turn
				// it will already have one by now if there is any valid target
				// but if there isn't one we need to choose a random slot now
				if (defender.fainted) {
					defender = this.sample(attacker.foes(true));
				}
				moveTargetLoc = attacker.getLocOf(defender);
			}
			attacker.volatiles[effect.id].targetLoc = moveTargetLoc;
			this.attrLastMove('[still]');
			// Run side-effects normally associated with hitting (e.g., Protean, Libero)
			this.runEvent('PrepareHit', attacker, defender, effect);
		},
		onEnd(target) {
			target.removeVolatile(this.effectState.move);
		},
		onLockMove() {
			return this.effectState.move;
		},
		onMoveAborted(pokemon) {
			pokemon.removeVolatile('twoturnmove');
		},
	},
	choicelock: {
		name: 'choicelock',
		noCopy: true,
		onStart(pokemon) {
			if (!this.activeMove) throw new Error("Battle.activeMove is null");
			if (!this.activeMove.id || this.activeMove.hasBounced || this.activeMove.sourceEffect === 'snatch') return false;
			this.effectState.move = this.activeMove.id;
		},
		onBeforeMove(pokemon, target, move) {
			if (!pokemon.getItem().isChoice) {
				pokemon.removeVolatile('choicelock');
				return;
			}
			if (
				!pokemon.ignoringItem() && !pokemon.volatiles['dynamax'] &&
				move.id !== this.effectState.move && move.id !== 'struggle'
			) {
				// Fails unless the Choice item is being ignored, and no PP is lost
				this.addMove('move', pokemon, move.name);
				this.attrLastMove('[still]');
				this.debug("Disabled by Choice item lock");
				this.add('-fail', pokemon);
				return false;
			}
		},
		onDisableMove(pokemon) {
			if (!pokemon.getItem().isChoice || !pokemon.hasMove(this.effectState.move)) {
				pokemon.removeVolatile('choicelock');
				return;
			}
			if (pokemon.ignoringItem() || pokemon.volatiles['dynamax']) {
				return;
			}
			for (const moveSlot of pokemon.moveSlots) {
				if (moveSlot.id !== this.effectState.move) {
					pokemon.disableMove(moveSlot.id, false, this.effectState.sourceEffect);
				}
			}
		},
	},
	mustrecharge: {
		name: 'mustrecharge',
		duration: 2,
		onBeforeMovePriority: 11,
		onBeforeMove(pokemon) {
			this.add('cant', pokemon, 'recharge');
			pokemon.removeVolatile('mustrecharge');
			pokemon.removeVolatile('truant');
			return null;
		},
		onStart(pokemon) {
			this.add('-mustrecharge', pokemon);
		},
		onLockMove: 'recharge',
	},
	futuremove: {
		// this is a slot condition
		name: 'futuremove',
		onStart(target) {
			this.effectState.targetSlot = target.getSlot();
			this.effectState.endingTurn = (this.turn - 1) + 2;
			if (this.effectState.endingTurn >= 254) {
				this.hint(`In Gen 8+, Future attacks will never resolve when used on the 255th turn or later.`);
			}
		},
		onResidualOrder: 3,
		onResidual(target: Pokemon) {
			if (this.getOverflowedTurnCount() < this.effectState.endingTurn) return;
			const slotTarget = this.getAtSlot(this.effectState.targetSlot);
			if (slotTarget.fainted && (this.effectState.moveData?.perfectForesight || this.effectState.moveData?.grandmasterForesight || this.effectState.moveData?.temporalShiftHex)) {
				this.effectState.endingTurn = this.turn + 1;
				this.add('-message', `${this.effectState.moveData.name} has no target and was delayed to turn ${this.effectState.endingTurn}.`);
				return;
			}
			target.side.removeSlotCondition(this.getAtSlot(this.effectState.targetSlot), 'futuremove');
		},
		onEnd(target) {
			const data = this.effectState;
			// time's up; time to hit! :D
			const move = this.dex.moves.get(data.move);
			if (data.moveData?.temporalShiftHex && data.source && (target === data.source || target.isAlly(data.source))) {
				const enemies = data.source.foes().filter(foe => foe.hp && !foe.fainted && foe !== data.source && !foe.isAlly(data.source));
				if (!enemies.length) {
					data.endingTurn = this.turn + 1;
					this.add('-message', `${move.name} has no enemy target and was delayed to turn ${data.endingTurn}.`);
					target.side.addSlotCondition(target, 'futuremove', data.source, this.dex.conditions.get('futuremove'));
					Object.assign(target.side.slotConditions[target.position]['futuremove'], data);
					return;
				}
				target = this.sample(enemies);
				this.add('-message', `${move.name} shifted to ${target.name}.`);
			}
			if ((target.fainted || target === data.source) && (data.moveData?.perfectForesight || data.moveData?.grandmasterForesight || data.moveData?.temporalShiftHex)) {
				data.endingTurn = this.turn + 1;
				this.add('-message', `${move.name} has no target and was delayed to turn ${data.endingTurn}.`);
				target.side.addSlotCondition(target, 'futuremove', data.source, this.dex.conditions.get('futuremove'));
				Object.assign(target.side.slotConditions[target.position]['futuremove'], data);
				return;
			}
			if (target.fainted || target === data.source) {
				this.hint(`${move.name} did not hit because the target is ${(target.fainted ? 'fainted' : 'the user')}.`);
				return;
			}

			this.add('-end', target, 'move: ' + move.name);
			target.removeVolatile('Protect');
			target.removeVolatile('Endure');

			if (data.source.hasAbility('infiltrator') && this.gen >= 6) {
				data.moveData.infiltrates = true;
			}
			if (data.source.hasAbility('normalize') && this.gen >= 6) {
				data.moveData.type = 'Normal';
			}
			const hitMove = new this.dex.Move(data.moveData) as ActiveMove;

			const hitResult = this.actions.trySpreadMoveHit([target], data.source, hitMove, true);
			if (!hitResult && data.moveData?.roarOfTimeFuture) {
				data.endingTurn = this.turn + 2;
				this.add('-message', `${move.name} missed and was sent further into the future, to turn ${data.endingTurn}.`);
				target.side.addSlotCondition(target, 'futuremove', data.source, this.dex.conditions.get('futuremove'));
				Object.assign(target.side.slotConditions[target.position]['futuremove'], data);
				return;
			}
			if (!hitResult && data.moveData?.temporalShiftHex) {
				data.endingTurn = this.turn + 1;
				this.add('-message', `${move.name} failed to hit and was delayed to turn ${data.endingTurn}.`);
				target.side.addSlotCondition(target, 'futuremove', data.source, this.dex.conditions.get('futuremove'));
				Object.assign(target.side.slotConditions[target.position]['futuremove'], data);
				return;
			}
			let requeuedFutureMove = false;
			if (data.moveData?.roarOfTimeFuture && data.roarOfTimeQueued > 1) {
				target.side.addSlotCondition(target, 'futuremove', data.source, this.dex.conditions.get('futuremove'));
				Object.assign(target.side.slotConditions[target.position]['futuremove'], {
					...data,
					endingTurn: this.turn + 1,
					roarOfTimeQueued: data.roarOfTimeQueued - 1,
				});
				requeuedFutureMove = true;
				this.add('-message', `${move.name} will strike again on turn ${this.turn + 1}.`);
			}
			if ((data.moveData?.perfectForesight || data.moveData?.grandmasterForesight || data.moveData?.temporalShiftHex) && data.perfectForesightQueued > 1) {
				target.side.addSlotCondition(target, 'futuremove', data.source, this.dex.conditions.get('futuremove'));
				Object.assign(target.side.slotConditions[target.position]['futuremove'], {
					...data,
					endingTurn: this.turn + 1,
					perfectForesightQueued: data.perfectForesightQueued - 1,
				});
				requeuedFutureMove = true;
				this.add('-message', `${move.name} will strike again on turn ${this.turn + 1}.`);
			}
			if (data.pendingRoarOfTime) {
				if (requeuedFutureMove) {
					const requeued = target.side.slotConditions[target.position]['futuremove'];
					if (requeued) requeued.pendingRoarOfTime = data.pendingRoarOfTime;
				} else {
					target.side.addSlotCondition(target, 'futuremove', data.pendingRoarOfTime.source, this.dex.conditions.get('futuremove'));
					Object.assign(target.side.slotConditions[target.position]['futuremove'], {
						move: 'roaroftime',
						source: data.pendingRoarOfTime.source,
						moveData: data.pendingRoarOfTime.moveData,
						endingTurn: this.turn + 1,
						roarOfTimeQueued: data.pendingRoarOfTime.count,
					});
					this.add('-message', `Roar of Time will strike on turn ${this.turn + 1}.`);
				}
			}
			if (data.source.isActive && data.source.hasItem('lifeorb') && this.gen >= 5) {
				this.singleEvent('AfterMoveSecondarySelf', data.source.getItem(), data.source.itemState, data.source, target, data.source.getItem());
			}
			this.activeMove = null;

			this.checkWin();
		},
	},
	healreplacement: {
		// this is a slot condition
		name: 'healreplacement',
		onStart(target, source, sourceEffect) {
			this.effectState.sourceEffect = sourceEffect;
			this.add('-activate', source, 'healreplacement');
		},
		onSwitchIn(target) {
			if (!target.fainted) {
				target.heal(target.maxhp);
				this.add('-heal', target, target.getHealth, '[from] move: ' + this.effectState.sourceEffect, '[zeffect]');
				target.side.removeSlotCondition(target, 'healreplacement');
			}
		},
	},
	stall: {
		// Protect, Detect, Endure counter
		name: 'stall',
		duration: 2,
		counterMax: 729,
		onStart() {
			this.effectState.counter = 3;
		},
		onStallMove(pokemon) {
			// this.effectState.counter should never be undefined here.
			// However, just in case, use 1 if it is undefined.
			const counter = this.effectState.counter || 1;
			this.debug(`Success chance: ${Math.round(100 / counter)}%`);
			const success = this.randomChance(1, counter);
			if (!success) delete pokemon.volatiles['stall'];
			return success;
		},
		onRestart() {
			if (this.effectState.counter < (this.effect as Condition).counterMax!) {
				this.effectState.counter *= 3;
			}
			this.effectState.duration = 2;
		},
	},
	gem: {
		name: 'gem',
		duration: 1,
		affectsFainted: true,
		onBasePowerPriority: 14,
		onBasePower(basePower, user, target, move) {
			this.debug('Gem Boost');
			return this.chainModify(1.3);
		},
	},

	// weather is implemented here since it's so important to the game

	raindance: {
		name: 'RainDance',
		effectType: 'Weather',
		duration: 5,
		durationCallback(source, effect) {
			if (source?.hasItem('damprock') || this.field.isTerrain(['bigtopterrain', 'coldeclipseterrain'])) {
				return 8;
			}
			return 5;
		},
		onWeatherModifyDamage(damage, attacker, defender, move) {
			if (defender.effectiveWeather() !== 'raindance') return;
			if (move.type === 'Water') {
				this.debug('rain water boost');
				return this.chainModify(1.5);
			}
			if (move.type === 'Fire') {
				this.debug('rain fire suppress');
				return this.chainModify(0.5);
			}
		},
		onFieldStart(field, source, effect) {
			if (this.field.weatherState?.previousWeather === 'sunnyday') {
				if (this.field.isTerrain('rainbowterrain')) {
					this.field.terrainState.duration = this.field.weatherState.duration;
				} else {
					this.field.setTerrain('rainbowterrain', source, effect);
				}
			}
			if (effect?.effectType === 'Ability') {
				if (this.gen <= 5) this.effectState.duration = 0;
				this.add('-weather', 'RainDance', '[from] ability: ' + effect.name, `[of] ${source}`);
			} else {
				this.add('-weather', 'RainDance');
			}
			this.field.terrainState.terrainChanges?.set('raindance', 1);
		},
		onFieldEnd() {
			this.field.terrainState.terrainChanges?.set('raindance', 0);
			this.add('-weather', 'none');
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			this.add('-weather', 'RainDance', '[upkeep]');
			this.eachEvent('Weather');
		},
	},
	primordialsea: {
		name: 'PrimordialSea',
		effectType: 'Weather',
		duration: 0,
		onTryMovePriority: 1,
		onTryMove(attacker, defender, move) {
			if (move.type === 'Fire' && move.category !== 'Status') {
				this.debug('Primordial Sea fire suppress');
				this.add('-fail', attacker, move, '[from] Primordial Sea');
				this.attrLastMove('[still]');
				return null;
			}
		},
		onWeatherModifyDamage(damage, attacker, defender, move) {
			if (defender.effectiveWeather() !== 'primordialsea') return;
			if (move.type === 'Water') {
				this.debug('Rain water boost');
				return this.chainModify(1.5);
			}
		},
		onFieldStart(field, source, effect) {
			this.add('-weather', 'PrimordialSea', '[from] ability: ' + effect.name, `[of] ${source}`);
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			this.add('-weather', 'PrimordialSea', '[upkeep]');
			this.eachEvent('Weather');
		},
		onFieldEnd() {
			this.add('-weather', 'none');
		},
	},
	sunnyday: {
		name: 'SunnyDay',
		effectType: 'Weather',
		duration: 5,
		durationCallback(source, effect) {
			if (source?.hasItem('heatrock') || this.field.isTerrain(['desertterrain', 'mountainterrain', 'snowymountainterrain'])) {
				return 8;
			}
			return 5;
		},
		onWeatherModifyDamage(damage, attacker, defender, move) {
			if (move.id === 'hydrosteam' && attacker.effectiveWeather() === 'sunnyday') {
				this.debug('Sunny Day Hydro Steam boost');
				return this.chainModify(1.5);
			}
			if (defender.effectiveWeather() !== 'sunnyday') return;
			if (move.type === 'Fire') {
				this.debug('Sunny Day fire boost');
				return this.chainModify(1.5);
			}
			if (move.type === 'Water') {
				this.debug('Sunny Day water suppress');
				return this.chainModify(0.5);
			}
		},
		onFieldStart(battle, source, effect) {
			if (this.field.weatherState?.previousWeather === 'raindance') {
				if (this.field.isTerrain('rainbowterrain')) {
					this.field.terrainState.duration = this.field.weatherState.duration;
				} else {
					this.field.setTerrain('rainbowterrain', source, effect);
				}
			}
			if (effect?.effectType === 'Ability') {
				if (this.gen <= 5) this.effectState.duration = 0;
				this.add('-weather', 'SunnyDay', '[from] ability: ' + effect.name, `[of] ${source}`);
			} else {
				this.add('-weather', 'SunnyDay');
			}
			this.field.terrainState.terrainChanges?.set('sunnyday', 1);
		},
		onImmunity(type, pokemon) {
			if (pokemon.effectiveWeather() !== 'sunnyday') return;
			if (type === 'frz') return false;
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			this.add('-weather', 'SunnyDay', '[upkeep]');
			this.eachEvent('Weather');
		},
		onFieldEnd() {
			this.field.terrainState.terrainChanges?.set('sunnyday', 0);
			this.add('-weather', 'none');
		},
	},
	desolateland: {
		name: 'DesolateLand',
		effectType: 'Weather',
		duration: 0,
		onTryMovePriority: 1,
		onTryMove(attacker, defender, move) {
			if (move.type === 'Water' && move.category !== 'Status') {
				this.debug('Desolate Land water suppress');
				this.add('-fail', attacker, move, '[from] Desolate Land');
				this.attrLastMove('[still]');
				return null;
			}
		},
		onWeatherModifyDamage(damage, attacker, defender, move) {
			if (defender.effectiveWeather() !== 'desolateland') return;
			if (move.type === 'Fire') {
				this.debug('Desolate Land fire boost');
				return this.chainModify(1.5);
			}
		},
		onFieldStart(field, source, effect) {
			this.add('-weather', 'DesolateLand', '[from] ability: ' + effect.name, `[of] ${source}`);
		},
		onImmunity(type, pokemon) {
			if (pokemon.effectiveWeather() !== 'desolateland') return;
			if (type === 'frz') return false;
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			this.add('-weather', 'DesolateLand', '[upkeep]');
			this.eachEvent('Weather');
		},
		onFieldEnd() {
			this.add('-weather', 'none');
		},
	},
	sandstorm: {
		name: 'Sandstorm',
		effectType: 'Weather',
		duration: 5,
		durationCallback(source, effect) {
			if (source?.hasItem('smoothrock') || this.field.isTerrain('desertterrain') || this.field.isTerrain('ashenbeachterrain')) {
				return 8;
			}
			return 5;
		},
		// This should be applied directly to the stat before any of the other modifiers are chained
		// So we give it increased priority.
		onModifySpDPriority: 10,
		onModifySpD(spd, pokemon) {
			if (pokemon.hasType('Rock') && this.field.isWeather('sandstorm')) {
				return this.modify(spd, 1.5);
			}
		},
		onFieldStart(field, source, effect) {
			if (effect?.effectType === 'Ability') {
				if (this.gen <= 5) this.effectState.duration = 0;
				this.add('-weather', 'Sandstorm', '[from] ability: ' + effect.name, `[of] ${source}`);
			} else {
				this.add('-weather', 'Sandstorm');
			}
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			if (this.field.isTerrain('rainbowterrain')) {
				this.field.clearTerrain();
			}
			this.add('-weather', 'Sandstorm', '[upkeep]');
			if (this.field.isWeather('sandstorm')) this.eachEvent('Weather');
		},
		onWeather(target) {
			if (this.field.isTerrain('desertterrain')) {
				this.damage(target.baseMaxhp / 8);
			} else {
				this.damage(target.baseMaxhp / 16);
			}
		},
		onFieldEnd() {
			this.add('-weather', 'none');
		},
	},
	hail: {
		name: 'Hail',
		effectType: 'Weather',
		duration: 5,
		durationCallback(source, target, effect) {
			if (this.field.isTerrain('fairytaleterrain')) return 0;
			if (effect?.id === 'mourningsnow') return 8;
			if (source?.hasItem('icyrock') || this.field.isTerrain(['icyterrain', 'snowymountainterrain', 'coldeclipseterrain'])) {
				return 8;
			}
			return 5;
		},
		onModifyDefPriority: 10,
		onModifyDef(def, pokemon) {
			const iceBeneficiary = pokemon.hasType('Ice') || (!pokemon.hasType('Ice') && pokemon.hasAbility(['mindfreeze', 'icebody', 'thickfat', 'toxicbloom', 'execution', 'argentdevotion', 'pollenbloom', 'wildfirecore', 'waterbarrage', 'atrocity', 'sunsovereign', 'siegelauncher', 'fortressshell']));
			if (iceBeneficiary && this.field.isWeather('hail')) {
				if (this.field.isTerrain('snowymountainterrain')) {
					return this.modify(def, 2.25);
				} else {
					return this.modify(def, 1.5);
				}
			}
		},
		onModifyMove(move) {
			if (move.secondaries) {
				this.debug('doubling frostbite chance');
				for (const secondary of move.secondaries) {
					if (secondary.chance && secondary.status === 'frz') secondary.chance *= 2;
				}
			}
		},
		onFieldStart(field, source, effect) {
			if (effect?.effectType === 'Ability') {
				if (this.gen <= 5) this.effectState.duration = 0;
				this.add('-weather', 'Hail', '[from] ability: ' + effect.name, `[of] ${source}`);
			} else {
				this.add('-weather', 'Hail');
			}
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			if (this.field.isTerrain('rainbowterrain')) {
				this.field.clearTerrain();
			}
			this.add('-weather', 'Hail', '[upkeep]');
			if (this.field.isWeather('hail')) this.eachEvent('Weather');
		},
		onWeather(target) {
			if (target.hasType('Ghost')) return;
			if (this.field.isTerrain('fairytaleterrain') && target.hasType(['Steel', 'Dragon', 'Fire'])) return;
			if (this.field.isTerrain('coldeclipseterrain')) {
				this.damage(target.baseMaxhp / 8);
			} else {
				this.damage(target.baseMaxhp / 16);
			}
		},
		onFieldEnd() {
			this.add('-weather', 'none');
		},
	},
	snowscape: {
		name: 'Snowscape',
		effectType: 'Weather',
		duration: 5,
		durationCallback(source, effect) {
			if (source?.hasItem('icyrock')) {
				return 8;
			}
			return 5;
		},
		onModifyDefPriority: 10,
		onModifyDef(def, pokemon) {
			if (pokemon.hasType('Ice') && this.field.isWeather('snowscape')) {
				return this.modify(def, 1.5);
			}
		},
		onFieldStart(field, source, effect) {
			if (effect?.effectType === 'Ability') {
				if (this.gen <= 5) this.effectState.duration = 0;
				this.add('-weather', 'Snowscape', '[from] ability: ' + effect.name, `[of] ${source}`);
			} else {
				this.add('-weather', 'Snowscape');
			}
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			this.add('-weather', 'Snowscape', '[upkeep]');
			if (this.field.isWeather('snowscape')) this.eachEvent('Weather');
		},
		onFieldEnd() {
			this.add('-weather', 'none');
		},
	},
	deltastream: {
		name: 'DeltaStream',
		effectType: 'Weather',
		duration: 0,
		durationCallback(target, source, effect) {
			if (effect?.id === 'tailwind') {
				return 6;
			}
			return 0;
		},
		onEffectivenessPriority: -1,
		onEffectiveness(typeMod, target, type, move) {
			if (move && move.effectType === 'Move' && move.category !== 'Status' && type === 'Flying' && typeMod > 0) {
				this.add('-fieldactivate', 'Delta Stream');
				return 0;
			}
		},
		onFieldStart(field, source, effect) {
			this.add('-weather', 'DeltaStream', '[from] ability: ' + effect.name, `[of] ${source}`);
		},
		onFieldResidualOrder: 1,
		onFieldResidual() {
			this.add('-weather', 'DeltaStream', '[upkeep]');
			this.eachEvent('Weather');
		},
		onFieldEnd() {
			this.add('-weather', 'none');
		},
	},

	dynamax: {
		name: 'Dynamax',
		noCopy: true,
		onStart(pokemon) {
			this.effectState.turns = 0;
			if (pokemon.gigantamax || pokemon.species.forme?.includes('Gmax')) {
				(pokemon as any).gmaxOriginalMoveSlots = pokemon.moveSlots.map(slot => ({ pp: slot.pp, maxpp: slot.maxpp, gmaxpp: null as number | null }));
				for (const [i, moveSlot] of pokemon.moveSlots.entries()) {
					const move = this.dex.moves.get(moveSlot.id);
					const maxMove = this.actions.getMaxMove(move, pokemon);
					if (maxMove?.name !== pokemon.canGigantamax) continue;
					(pokemon as any).gmaxOriginalMoveSlots[i].gmaxpp = 8;
					moveSlot.pp = 8;
					moveSlot.maxpp = 8;
				}
				for (const volatile of Object.keys(pokemon.volatiles)) {
					if (volatile !== 'dynamax') pokemon.removeVolatile(volatile);
				}
				if (!(pokemon as any).gmaxTransformHealed) {
					(pokemon as any).gmaxTransformHealed = true;
					this.heal(pokemon.baseMaxhp / 10, pokemon, pokemon);
				}
			}
			pokemon.removeVolatile('minimize');
			pokemon.removeVolatile('substitute');
			if (pokemon.volatiles['torment']) {
				delete pokemon.volatiles['torment'];
				this.add('-end', pokemon, 'Torment', '[silent]');
			}
			if (['cramorantgulping', 'cramorantgorging'].includes(pokemon.species.id) && !pokemon.transformed) {
				pokemon.formeChange('cramorant');
			}
			if (pokemon.baseSpecies.name === 'Shedinja') return;
		},
		onTryAddVolatile(status, pokemon) {
			if (status.id === 'flinch') return null;
		},
		onSourceModifyDamage(damage, source, target, move) {
			if (move.id === 'behemothbash' || move.id === 'behemothblade' || move.id === 'dynamaxcannon') {
				return this.chainModify(2);
			}
		},
		onDragOutPriority: 2,
		onDragOut(pokemon) {
			this.add('-block', pokemon, 'Dynamax');
			return null;
		},
		onResidualPriority: -100,
		onResidual() {
			this.effectState.turns++;
		},
		onEnd(pokemon) {
			const originalMoveSlots = (pokemon as any).gmaxOriginalMoveSlots;
			if (!originalMoveSlots) return;
			for (const [i, originalSlot] of originalMoveSlots.entries()) {
				if (!pokemon.moveSlots[i]) continue;
				if (originalSlot.gmaxpp === null) continue;
				const spentPP = this.clampIntRange(originalSlot.gmaxpp - pokemon.moveSlots[i].pp, 0, originalSlot.gmaxpp);
				const restoredPP = this.clampIntRange(originalSlot.pp - spentPP, 0, originalSlot.maxpp);
				pokemon.moveSlots[i].pp = restoredPP;
				pokemon.moveSlots[i].maxpp = originalSlot.maxpp;
				if (pokemon.baseMoveSlots[i]) {
					pokemon.baseMoveSlots[i].pp = restoredPP;
					pokemon.baseMoveSlots[i].maxpp = originalSlot.maxpp;
				}
			}
			delete (pokemon as any).gmaxOriginalMoveSlots;
		},
	},

	// Commander needs two conditions so they are implemented here
	// Dondozo
	commanded: {
		name: "Commanded",
		noCopy: true,
		onStart(pokemon) {
			this.boost({ atk: 2, spa: 2, spe: 2, def: 2, spd: 2 }, pokemon);
		},
		onDragOutPriority: 2,
		onDragOut() {
			return false;
		},
		// Prevents Shed Shell allowing a swap
		onTrapPokemonPriority: -11,
		onTrapPokemon(pokemon) {
			pokemon.trapped = true;
		},
	},
	// Tatsugiri
	commanding: {
		name: "Commanding",
		noCopy: true,
		onDragOutPriority: 2,
		onDragOut() {
			return false;
		},
		// Prevents Shed Shell allowing a swap
		onTrapPokemonPriority: -11,
		onTrapPokemon(pokemon) {
			pokemon.trapped = true;
		},
		// Dodging moves is handled in BattleActions#hitStepInvulnerabilityEvent
		// This is here for moves that manually call this event like Perish Song
		onInvulnerability: false,
		onBeforeTurn(pokemon) {
			this.queue.cancelAction(pokemon);
		},
	},

	// Arceus and Silvally's actual typing is implemented here.
	// Their true typing for all their formes is Normal, and it's only
	// Multitype and RKS System, respectively, that changes their type,
	// but their formes are specified to be their corresponding type
	// in the Pokedex, so that needs to be overridden.
	// This is mainly relevant for Hackmons Cup and Balanced Hackmons.
	arceus: {
		name: 'Arceus',
		onTypePriority: 1,
		onSwitchIn(pokemon) {
			if (this.field.isTerrain('newworldterrain') && pokemon.ability === 'multitype') {
				const types = ['Grass', 'Fire', 'Water', 'Electric', 'Ice', 'Dragon', 'Psychic', 'Normal', 'Fighting', 'Ghost', 'Poison', 'Bug', 'Flying', 'Ground', 'Rock', 'Dark', 'Steel', 'Fairy'];
				const new_type = this.sample(types);
				pokemon.setType(new_type, true);
				this.add('-start', pokemon, 'typechange', new_type);
			}
		},
		onType(types, pokemon) {
			if (pokemon.transformed || pokemon.ability !== 'multitype' && this.gen >= 8 || this.field.isTerrain('glitchterrain') || this.field.isTerrain('holyterrain') || this.field.isTerrain('newworldterrain')) return types;
			let type: string | undefined = 'Normal';
			if (pokemon.ability === 'multitype') {
				if (this.field.isTerrain('newworldterrain')) {
					const existingTypes = ['Grass', 'Fire', 'Water', 'Electric', 'Ice', 'Dragon', 'Psychic', 'Normal', 'Fighting', 'Ghost', 'Poison', 'Bug', 'Flying', 'Ground', 'Rock', 'Dark', 'Steel', 'Fairy'];
					type = this.sample(existingTypes);
				} else {
					type = pokemon.getItem().onPlate;
				}
				if (!type) {
					type = 'Normal';
				}
			}
			return [type];
		},
		onResidual(pokemon) {
			if (this.field.isTerrain('newworldterrain')) {
				const types = ['Grass', 'Fire', 'Water', 'Electric', 'Ice', 'Dragon', 'Psychic', 'Normal', 'Fighting', 'Ghost', 'Poison', 'Bug', 'Flying', 'Ground', 'Rock', 'Dark', 'Steel', 'Fairy'];
				const new_type = this.sample(types);
				pokemon.setType(new_type, true);
				this.add('-start', pokemon, 'typechange', new_type);
			}
		},
	},
	silvally: {
		name: 'Silvally',
		updateSilvallyForme(pokemon, type) {
			if (pokemon.transformed || pokemon.terastallized) return;
			const typeid = type === '???' ? 'unknown' : toID(type);
			const forme = typeid === 'normal' || typeid === 'unknown' ? 'Silvally' : `Silvally-${type}`;
			if (pokemon.species.name !== forme && this.dex.species.get(forme).exists) {
				pokemon.formeChange(forme, this.dex.conditions.get('silvally'), false, '[silent]');
			}
		},
		onTypePriority: 1,
		onSwitchIn(pokemon) {
			if (pokemon.ability === 'rkssystem') {
				if (this.field.isTerrain('glitchterrain')) {
					pokemon.setType('???', true);
					this.add('-start', pokemon, 'typechange', '???');
					this.effect.updateSilvallyForme.call(this, pokemon, '???');
				} else if (this.field.isTerrain('holyterrain')) {
					pokemon.setType('Dark', true);
					this.add('-start', pokemon, 'typechange', 'Dark');
					this.effect.updateSilvallyForme.call(this, pokemon, 'Dark');
				} else if (this.field.isTerrain('newworldterrain')) {
					const types = ['Grass', 'Fire', 'Water', 'Electric', 'Ice', 'Dragon', 'Psychic', 'Normal', 'Fighting', 'Ghost', 'Poison', 'Bug', 'Flying', 'Ground', 'Rock', 'Dark', 'Steel', 'Fairy'];
					const new_type = this.sample(types);
					pokemon.setType(new_type, true);
					this.add('-start', pokemon, 'typechange', new_type);
					this.effect.updateSilvallyForme.call(this, pokemon, new_type);
				} else {
					const itemType = pokemon.getItem().onMemory || pokemon.getItem().zMoveType || 'Normal';
					this.effect.updateSilvallyForme.call(this, pokemon, itemType);
				}
			}
		},
		onType(types, pokemon) {
			if (pokemon.transformed || pokemon.ability !== 'rkssystem' || this.field.isTerrain('glitchterrain') || this.field.isTerrain('holyterrain') || this.field.isTerrain('newworldterrain')) return types;
			let type: string | undefined = 'Normal';
			if (pokemon.ability === 'rkssystem') {
				const item = pokemon.getItem();
				type = item.onMemory || item.zMoveType;
				if (!type) {
					type = 'Normal';
				}
			}
			return [type];
		},
		onResidual(pokemon) {
			if (pokemon.ability === 'rkssystem') {
				if (this.field.isTerrain('glitchterrain') && pokemon.types[0] !== '???') {
					pokemon.setType('???', true);
					this.add('-start', pokemon, 'typechange', '???');
					this.effect.updateSilvallyForme.call(this, pokemon, '???');
				} else if (this.field.isTerrain('newworldterrain')) {
					const types = ['Grass', 'Fire', 'Water', 'Electric', 'Ice', 'Dragon', 'Psychic', 'Normal', 'Fighting', 'Ghost', 'Poison', 'Bug', 'Flying', 'Ground', 'Rock', 'Dark', 'Steel', 'Fairy'];
					const new_type = this.sample(types);
					pokemon.setType(new_type, true);
					this.add('-start', pokemon, 'typechange', new_type);
					this.effect.updateSilvallyForme.call(this, pokemon, new_type);
				} else if (!this.field.isTerrain('holyterrain') && pokemon.ability === 'rkssystem') {
					const itemType = pokemon.getItem().onMemory || pokemon.getItem().zMoveType;
					if (itemType === undefined) {
						this.effect.updateSilvallyForme.call(this, pokemon, 'Normal');
						return;
					}
					pokemon.setType(itemType, true);
					if (itemType !== pokemon.getTypes()[0] && pokemon.getTypes().length === 1) {
						this.add('-start', pokemon, 'typechange', itemType);
					}
					this.effect.updateSilvallyForme.call(this, pokemon, itemType);
				}
			}
		},
	},
	zacian: {
		name: 'Zacian',
		onBattleStart(pokemon) {
			if (pokemon.item !== 'rustedsword') return;
			const rawSpecies = this.dex.species.get('Zacian-Crowned');
			const species = pokemon.setSpecies(rawSpecies);
			if (!species) return;
			pokemon.baseSpecies = rawSpecies;
			pokemon.details = pokemon.getUpdatedDetails();
			pokemon.setAbility(species.abilities['0'], null, null, true);
			pokemon.baseAbility = pokemon.ability;

			const ironHeadIndex = pokemon.baseMoves.indexOf('ironhead');
			if (ironHeadIndex >= 0) {
				const move = this.dex.moves.get('behemothblade');
				const pp = this.calculatePP(move, pokemon.ppUps[ironHeadIndex]);
				pokemon.baseMoveSlots[ironHeadIndex] = {
					move: move.name,
					id: move.id,
					pp,
					maxpp: pp,
					target: move.target,
					disabled: false,
					disabledSource: '',
					used: false,
				};
				pokemon.moveSlots = pokemon.baseMoveSlots.slice();
			}
		},
	},
	zamazenta: {
		name: 'Zamazenta',
		onBattleStart(pokemon) {
			if (pokemon.item !== 'rustedshield') return;
			const rawSpecies = this.dex.species.get('Zamazenta-Crowned');
			const species = pokemon.setSpecies(rawSpecies);
			if (!species) return;
			pokemon.baseSpecies = rawSpecies;
			pokemon.details = pokemon.getUpdatedDetails();
			pokemon.setAbility(species.abilities['0'], null, null, true);
			pokemon.baseAbility = pokemon.ability;

			const ironHeadIndex = pokemon.baseMoves.indexOf('ironhead');
			if (ironHeadIndex >= 0) {
				const move = this.dex.moves.get('behemothbash');
				const pp = this.calculatePP(move, pokemon.ppUps[ironHeadIndex]);
				pokemon.baseMoveSlots[ironHeadIndex] = {
					move: move.name,
					id: move.id,
					pp,
					maxpp: pp,
					target: move.target,
					disabled: false,
					disabledSource: '',
					used: false,
				};
				pokemon.moveSlots = pokemon.baseMoveSlots.slice();
			}
		},
	},

	rolloutstorage: {
		name: 'rolloutstorage',
		duration: 2,
		onBasePower(relayVar, source, target, move) {
			let bp = Math.max(1, move.basePower);
			bp *= 2 ** source.volatiles['rolloutstorage'].contactHitCount;
			if (source.volatiles['defensecurl']) {
				bp *= 2;
			}
			source.removeVolatile('rolloutstorage');
			return bp;
		},
	},
	tormented: {
		name: "Tormented",
		duration: 9999,
		onResidual(target, source, effect) {
			this.add('-message', 'Fell\'s Pokemon is feeling the same pain that he inflicted on Tern!');
			this.damage(target.baseMaxhp / 24, target);
		},
	},
};
